labassign/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('convalidation/', views.convalidation, name='convalidation'),
    path('applypair/', views.applypair, name='applypair'),
    path('elegir_grupo/', views.elegir_grupo, name='elegir_grupo'),
    path('breakpair/', views.breakpair, name='breakpair'),    
]

labassign/labassign/urls.py
from django.contrib import admin
from django.urls import path
from core import views
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL,\
                      document_root=settings.STATIC_ROOT)

labassign/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db.models.functions import Upper


class Teacher(models.Model):
    first_name = models.CharField(blank=False, max_length=50)
    last_name = models.CharField(blank=False, max_length=50)

    class Meta:
        ordering = [Upper('last_name'), 'first_name']

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class LabGroup(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    groupName = models.CharField(blank=False, max_length=50, unique=True)
    language = models.CharField(blank=False, max_length=50)
    schedule = models.CharField(blank=False, max_length=150)
    maxNumberStudents = models.IntegerField(default=1)
    counter = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if(self.maxNumberStudents < 0):
            self.maxNumberStudents = 0

        super(LabGroup, self).save(*args, **kwargs)

    def __str__(self):
        return self.groupName


class TheoryGroup(models.Model):
    groupName = models.CharField(blank=False, max_length=50, unique=True)
    language = models.CharField(blank=False, max_length=50)

    class Meta:
        ordering = ['groupName']

    def __str__(self):
        return self.groupName


class Student(AbstractUser):
    labGroup = models.ForeignKey(LabGroup, on_delete=models.CASCADE, null=True)
    theoryGroup = models.ForeignKey(
        TheoryGroup,
        on_delete=models.CASCADE,
        null=True)
    gradeTheoryLastYear = models.FloatField(default=0.0)
    gradeLabLastYear = models.FloatField(default=0.0)
    convalidationGranted = models.BooleanField(default=False)
    # Flag para comprobar que el estudiante ha seleccionado una pareja
    es_pareja = models.IntegerField(default=0)
    # Flag para comprobar que el estudiante está en una pareja validada
    es_pareja_validada = models.IntegerField(default=0)
    # Flag para comprobar que el estudiante está en un grupo de laboratorio
    esta_grupo = models.IntegerField(default=0)

    class Meta:
        ordering = [Upper('last_name'), 'first_name']

    def save(self, *args, **kwargs):
        if(self.gradeTheoryLastYear < 0.0):
            self.gradeTheoryLastYear = 0.0

        if(self.gradeLabLastYear < 0):
            self.gradeLabLastYear = 0
        super(Student, self).save(*args, **kwargs)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class OtherConstraints(models.Model):
    selectGroupStartDate = models.DateTimeField(default=timezone.now)
    minGradeTheoryConv = models.FloatField(blank=True, default=0.0)
    minGradeLabConv = models.FloatField(blank=True, default=0.0)

    def save(self, *args, **kwargs):
        if (self.minGradeTheoryConv < 0.0):
            self.minGradeTheoryConv = 0
        if (self.minGradeLabConv < 0.0):
            self.minGradeLabConv = 0
        if(self.selectGroupStartDate < timezone.now()):
            self.selectGroupStartDate = timezone.now()
        super(OtherConstraints, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.minGradeLabConv) + str(self.minGradeTheoryConv)


class GroupConstraints(models.Model):
    theoryGroup = models.ForeignKey(TheoryGroup, on_delete=models.CASCADE)
    labGroup = models.ForeignKey(LabGroup, on_delete=models.CASCADE)

    class Meta:
        ordering = ['labGroup', 'theoryGroup']

    def __str__(self):
        return self.theoryGroup.groupName + ', ' + self.labGroup.groupName


class Pair(models.Model):
    student1 = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='student1')
    student2 = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='student2')
    validated = models.BooleanField(default=False)
    studentBreakRequest = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        null=True)

    def __str__(self):
        return "\nstudent1 --> (%d) %s, %s \n" \
               "student2 --> (%d) %s, %s. Val =%r\n" % \
               (self.student1.id, self.student1.last_name,
                self.student1.first_name, self.student2.id,
                self.student2.last_name, self.student2.first_name,
                self.validated)

    class Meta:
        ordering = ['student1__id', 'student2__id']

labassign/core/forms.py
from django import forms
from core.models import Pair, Student

MAX_LENGTH = 128


class PairForm(forms.ModelForm):
    class Meta:
        model = Pair
        exclude = ('studentBreakRequest', 'validated')


class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Student
        fields = ('username',
                  'password',
                  'first_name',
                  'last_name',
                  'gradeTheoryLastYear',
                  'gradeLabLastYear',
                  'labGroup',
                  'theoryGroup',
                  'convalidationGranted')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Student
        fields = ('username', 'password')

labassign/core/views.py
from django.shortcuts import render, redirect
from core.models import (Pair, Student,
                         OtherConstraints,
                         GroupConstraints,
                         LabGroup)
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone


def home(request):
    """
    Función que retorna la vista en la web de la página de inicio,
        con la información necesaria para visualizar la información
        del estudiante.
    Autor: Elena Diego
    """
    pairs = Pair.objects.all()
    context_dict = {}
    context_dict['pairs'] = pairs
    return render(request, 'core/home.html', context_dict)


@login_required
def convalidation(request):
    """
    Función que procesa la convalidación de las prácticas de un
        estudiante en base a las condiciones dadas.
    Autor: Ángel Bernal
    """
    st_theory = request.user.gradeTheoryLastYear
    st_lab = request.user.gradeLabLastYear

    ot = OtherConstraints.objects.all().first()
    min_theory = ot.minGradeTheoryConv
    min_lab = ot.minGradeLabConv

    if st_theory >= min_theory and st_lab >= min_lab:
        request.user.convalidationGranted = True
        request.user.save()

    return render(request, 'core/convalidation.html')


@login_required
def applypair(request):
    """
    Función que, si no viene del formulario de elegir pareja,
        devuelve la vista de la página web applypair en la que
        se visualiza las posibles parejas entre las que el usuario
        puede elegir.
        Si viene desde el formulario (con el request.method='POST')
        se procesa la petición de la pareja, creandola en el caso de
        que solo el estudiante1 la haya pedido y validándola si es el
        estudiante2 de la pareja la que lo solicita.
    Autor: Elena Diego
    """
    if request.method == 'POST':
        if request.user.es_pareja == 1:
            students = Student.objects.all().exclude(es_pareja_validada=1)
            students_final = students.exclude(username=request.user.username)
            pareja_mismo_usuario = "User has already selected a pair"
            context_dict = {}
            context_dict['students'] = students_final
            context_dict['pareja_mismo_usuario'] = pareja_mismo_usuario
            return render(request, 'core/applypair.html', context_dict)

        user1 = request.user
        user2_id = request.POST.get("colegas")
        user2 = Student.objects.get(id=user2_id)
        try:
            pareja = Pair.objects.get(student1=user2, student2=user1)
            pareja.validated = True
            pareja.save()
            user1.es_pareja = 1
            user1.es_pareja_validada = 1
            user1.save()
            user2.es_pareja_validada = 1
            user2.save()

        except ObjectDoesNotExist:
            Pair.objects.create(student1=user1, student2=user2)
            user1.es_pareja = 1
            user1.save()

        return redirect(reverse('core:home'))

    if request.user.es_pareja == 1:
        return redirect(reverse('core:home'))

    if request.user.convalidationGranted is True:
        convalidado = "Ya estás convalidado"
        students = Student.objects.all().exclude(es_pareja_validada=1)
        students_final = students.exclude(username=request.user.username)
        context_dict = {}
        context_dict['students'] = students_final
        context_dict['convalidado'] = convalidado
        return render(request, 'core/home.html', context_dict)

    students = Student.objects.all().exclude(es_pareja_validada=1)
    students_final = students.exclude(username=request.user.username)
    context_dict = {}
    context_dict['students'] = students_final
    return render(request, 'core/applypair.html', context_dict)


@login_required
def elegir_grupo(request):
    """
    Función que, si no viene del formulario de elegir grupo,
        devuelve la vista de la página web elegir_grupo en la que
        se visualiza los posibles grupos de laboratorio entre los
        que el usuario puede elegir.
        Si viene desde el formulario (con el request.method='POST')
        se procesa la petición del grupo, añadiendo al estudiante si no
        tiene pareja y hay espacio o añadiendo también a su pareja siempre que
        haya dos espacios libres en el grupo.
    Autor: Ángel Bernal
    """
    if request.method == 'POST':
        user1 = request.user
        grupo_id = request.POST.get("grupo")
        grupo = LabGroup.objects.get(id=grupo_id)
        if GroupConstraints.objects.filter(labGroup=grupo,
                                           theoryGroup=user1.theoryGroup).exists() is False:
            grupo_std = request.user.theoryGroup
            grupos_lab = GroupConstraints.objects.filter(theoryGroup=grupo_std)
            for g in grupos_lab:
                if g.labGroup.counter >= g.labGroup.maxNumberStudents:
                    grupos_lab = grupos_lab.exclude(id=g.id)
            aux = OtherConstraints.objects.all().first().selectGroupStartDate
            if timezone.now() < aux:
                valido = 0
            else:
                valido = 1
            context_dict = {}
            context_dict['grupos_lab'] = grupos_lab
            context_dict['valido'] = valido
            context_dict['error'] = "Grupo de prácticas no válido"
            return render(request, 'core/elegir_grupo.html', context_dict)

        if(Pair.objects.filter(student1=user1,
                               validated=True).exists() is True):
            user2 = Pair.objects.get(student1=user1, validated=True).student2
            if((grupo.maxNumberStudents-grupo.counter) >= 2):
                user1.labGroup = grupo
                user2.labGroup = grupo
                user1.esta_grupo = 1
                user1.save()
                user2.esta_grupo = 1
                user2.save()
                grupo.counter += 2
                grupo.save()

        elif(Pair.objects.filter(student2=user1,
                                 validated=True).exists() is True):
            user2 = Pair.objects.get(student2=user1, validated=True).student1
            if((grupo.maxNumberStudents-grupo.counter) >= 2):
                user1.labGroup = grupo
                user2.labGroup = grupo
                user1.esta_grupo = 1
                user1.save()
                user2.esta_grupo = 1
                user2.save()
                grupo.counter += 2
                grupo.save()

        if(grupo.maxNumberStudents > grupo.counter and user1.esta_grupo == 0):
            user1.labGroup = grupo
            user1.esta_grupo = 1
            user1.save()
            grupo.counter += 1
            grupo.save()
        return redirect(reverse('core:home'))

    grupo_student = request.user.theoryGroup
    grupos_lab = GroupConstraints.objects.filter(theoryGroup=grupo_student)
    for g in grupos_lab:
        if g.labGroup.counter >= g.labGroup.maxNumberStudents:
            grupos_lab = grupos_lab.exclude(id=g.id)
    aux = OtherConstraints.objects.all().first().selectGroupStartDate
    if timezone.now() < aux:
        valido = 0
    else:
        valido = 1
    context_dict = {}
    context_dict['grupos_lab'] = grupos_lab
    context_dict['valido'] = valido
    return render(request, 'core/elegir_grupo.html', context_dict)


@login_required
def breakpair(request):
    if request.method == "POST":
        error = 0
        pair_id = request.POST.get("parejas")
        try:
            pair = Pair.objects.get(id=pair_id)
            if pair.validated is False:
                pair.delete()
                request.user.es_pareja = 0
                request.user.save()
            else:
                if(pair.studentBreakRequest is None):
                    pair.studentBreakRequest = request.user
                    pair.save()
                elif (pair.studentBreakRequest is not None
                      and pair.studentBreakRequest is not request.user):
                    pair.delete()

        except ObjectDoesNotExist:
            error = 1

        parejas_user1 = Pair.objects.filter(student1=request.user)
        parejas_user2 = Pair.objects.filter(student2=request.user)
        parejas_user1 |= parejas_user2
        context_dict = {}
        context_dict['parejas_user'] = parejas_user1
        if error == 1:
            error_breakpair = 'Could not process your request'
            context_dict['error_breakpair'] = error_breakpair
        return render(request, 'core/breakpair.html', context_dict)

    parejas_user1 = Pair.objects.filter(student1=request.user)
    parejas_user2 = Pair.objects.filter(student2=request.user)
    parejas_user1 |= parejas_user2
    context_dict = {}
    context_dict['parejas_user'] = parejas_user1
    return render(request, 'core/breakpair.html', context_dict)

labassign/templates/core/applypair.html
{% extends 'core/base.html' %}

{%block title_block %}
    Apply pair
{% endblock %}

{% block body_block %}
    <h1>Apply Pair</h1>
    {% if pareja_mismo_usuario %}
        {{pareja_mismo_usuario}}

    {% else %}
    <p class="contenido">Select the second</p>
    <p class="contenido">Por favor, elija su compañero de prácticas.<br>
    Para que la pareja sea validada su compañero deberá volver a hacer el proceso y elegirlo.</p>
    <div class="contenido">
        <form id="eleccion" name="eleccion" method="POST" action="{% url 'core:applypair' %}">
            {% csrf_token %}
            <label for="companero">Elige un compañero:</label>

            <select name="colegas" id="colegas">
                {% for s in students %}
                    <option id="seleccion" name="seleccion" value={{s.id}}>>{{s.last_name}}, {{s.first_name}}</option>
                {% endfor %}
            </select> 

            <input class="elegir" type="submit" value="Elegir" />
        </form>
    </div>
    {%endif%}
{% endblock %}

labassign/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head lang="en">
        <link rel="stylesheet" href="{% static "css/base.css" %}"/>
        <meta charset="UTF-8"/>
        <title>
            Core -
            {% block title_block %}
               
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <br/>
        </br>
        </br>
        <div id="lista">
                {% if user.is_authenticated %}
                <a class="lista" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <a class="lista" href="{% url 'login' %}">Login</a></li>
                {% endif %}
                <a class="lista" href="{% url 'core:home' %}">Index</a></li>
        </div>
        <br>
        <div class="derechos">Desarrollado por Elena y Ángel (All rights reserved)</div>
    </body>
</html>

labassign/templates/core/breakpair.html
{% extends 'core/base.html' %}

{%block title_block %}
    Break pair
{% endblock %}

{% block body_block %}
    <h1>Break Pair</h1>
    
    <p class="contenido">Select the pair to be</p>
    <div class="contenido">
        Si la pareja está validada su compañero tendrá que hacer el mismo proceso y romper la pareja.
        <form id="break" name="break" method="POST" action="{% url 'core:breakpair' %}">
            {% csrf_token %}
            <label for="companero">Elige la pareja que quiere romper:</label>

            <select name="parejas" id="parejas">
                {% for p in parejas_user %}
                    <option id="seleccion" name="seleccion" value={{p.id}}>>{{p.student1}}, {{p.student2}}</option>
                {% endfor %}
            </select> 

            <input class="elegir" type="submit" value="Elegir" />
        </form>
        {{ error_breakpair }}
    </div>
{% endblock %}

labassign/templates/core/convalidation.html
{% extends 'core/base.html' %}

{%block title_block %}
    Convalidation
{% endblock %}

{% block body_block %}
    <h1>Convalidation</h1>
    <div class="contenido">
        {% if user.convalidationGranted == True %}
            You satisfy them.
        {% else %}
            do not satify
        {% endif %}
    </div>
{% endblock %}

labassign/templates/core/elegir_grupo.html
{% extends 'core/base.html' %}

{%block title_block %}
    Apply pair
{% endblock %}

{% block body_block %}
    <h1>Apply Group</h1>
    <p class="contenido"> Select the group you want to join to</p>
    <p class="contenido">Elija su grupo de prácticas.<br>
        Si tiene pareja su compañero también será introducido en el mismo.<br>
        Solamente podrá optar a los grupos correspondientes a su grupo de teoría.
    </p>
    <div class="contenido">
        {% if valido == 1 %}
        <form id="grupo_form" name="grupo_form" method="POST" action="{% url 'core:elegir_grupo' %}">
            {% csrf_token %}
            <label for="label">Elige un grupo:</label>

            <select name="grupo" id="grupo">
                {% for g in grupos_lab %}
                    <option id="grupo" name="grupo" value={{g.id}}>>{{g.id}}</option>
                {% endfor %}
            </select> 
            <input class="elegir" type="submit" value="Elegir" />
        </form>
        {{ error }}
        {% else %}
            <p>Group selection is not active</p>
        {% endif %}
    </div>
{% endblock %}

labassign/templates/core/home.html
{% extends 'core/base.html' %}

{%block title_block %}
    Home
{% endblock %}

{% block body_block %}
    <h1>Home</h1>
    <div class="contenido">
        <div class="informacion">
        {% if user.is_authenticated %}
            <p id="summary">Summary page for <b>{{ user.first_name }}</b></br></p>
            Nombre: <div id="nombre">{{ user.first_name }}</div>
            </br>
            Apellidos: <div id="apellidos">{{ user.last_name }}</div>
            </br>
            Estado de convalidación: <div id="informacion">{{ user.convalidationGranted }}</div>
            </br>
            Grupo practicas: <div id="informacion">{{ user.labGroup }}</div>
            </br>
            {% for p in pairs %}
                {% if user.id == p.student1.id or user.id == p.student2.id%}
                    Pareja:
                    </br>
                    - Estudiante 1: <div id="nombre">{{ p.student1.first_name }} {{ p.student1.last_name }}</div>
                    </br>
                    - Estudiante 2: <div id="apellidos">{{ p.student2.first_name }} {{ p.student2.last_name }}</div>
                    </br>
                    - Validated: <div id="grupo">{{ p.validated }}</div>
                </br>
            </br>
                {% endif %}
            {% endfor %}
        </div>  
        
            {% if user.es_pareja == 0 %}
                {% if user.convalidationGranted == False %}
                    <p>
                        Para optar a la convalidación necesita una nota<br>
                        mínima del año pasado de teoría de 3.0 y de prácticas 7.0
                    </p>
                    <form  id="convalidation" method="POST" action="{% url 'core:convalidation' %}">
                        {% csrf_token %}
                        <input type="hidden" id="username" name="username" value={{user.username}} />
                        <input type="submit" class="boton" value="Convalidation" />
                    </form>
                {% endif %}
                <br>
                <a href="{% url 'core:applypair' %}"> <button class="boton" type="button">Elige un compañero</button></a>
                {{ convalidado }}
            {% endif %}
            </br></br>
            
            {% if user.esta_grupo == 0 %}
                <a href="{% url 'core:elegir_grupo' %}"> <button class="boton" type="button">Elige un grupo</button></a>
                {% if user.es_pareja == 1 %}
                        <a href="{% url 'core:breakpair' %}"> <button class="boton" type="button">Romper pareja</button></a>
                {% endif %}
            {% endif %}
        {% else %}
            Bienvenido, por favor, inicie sesión.
        {% endif %}
    </div>
{% endblock %}

labassign/templates/core/login.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Core
        </title>
    </head>
    <body>
        <div>
            <h1>Login</h1>
            <form id="login_form" method="post" action="{% url 'core:login' %}">
                {% csrf_token %}
                Username: <input type="text" name="username" value="" size="50" />
                <br />
                Password: <input type="password" name="password" value="" size="50" />
                <br />
                <input type="submit" value="submit" />
            </form>
        </div>
        <a href="{% url 'core:home' %}">Home</a>
    </body>
</html>